#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List

HEADER_RUST = """// AUTO-GENERATED FILE. Do not edit by hand.
// Generated by tools/generate_tauri_wrappers.py
use std::process::Command;
use std::path::PathBuf;

fn bin_dir() -> PathBuf {
  let mut p = std::env::current_exe().unwrap_or_else(|_| PathBuf::from("."));
  p.pop(); // exe
  p.push("bin"); // optional co-located tools
  p
}

fn script_path(rel: &str) -> PathBuf {
  let mut p = std::env::current_exe().unwrap_or_else(|_| PathBuf::from("."));
  p.pop();
  p.push(rel);
  p
}

fn sanitize_arg(arg: &str) -> Result<(), String> {
  // Very basic guard; improve as needed
  if arg.contains('\n') || arg.contains('\r') {
    return Err("invalid argument".into());
  }
  Ok(())
}
"""

HEADER_TS = """// AUTO-GENERATED FILE. Do not edit by hand.
// Generated by tools/generate_tauri_wrappers.py
import { invoke } from "@tauri-apps/api/tauri";
"""

def rust_cmd_for(entry: Dict[str, Any]) -> str:
  name = entry["name"]
  func = name.replace(".", "_").replace("-", "_")
  rel = entry["path"]
  stype = entry["script_type"]
  flags: List[str] = entry.get("arg_flags", [])
  # Define a generic arg map: record<string, string>
  rust = []
  rust.append(f"#[tauri::command]")
  rust.append(
    f"pub async fn run_legacy_{func}(args: Vec<String>) -> Result<String, String> {{"
  )
  rust.append("  for a in &args { sanitize_arg(a)?; }")

  if stype == "python":
    rust.append("  let mut cmd = Command::new(if cfg!(target_os=\"windows\") { \"python\" } else { \"python3\" });")
    rust.append(f"  cmd.arg(script_path(\"{rel}\"));")
  elif stype == "bash":
    rust.append("  let mut cmd = Command::new(if cfg!(target_os=\"windows\") { \"bash\" } else { \"bash\" });")
    rust.append(f"  cmd.arg(script_path(\"{rel}\"));")
  elif stype == "powershell":
    rust.append("  let mut cmd = Command::new(\"powershell\");")
    rust.append("  cmd.arg(\"-ExecutionPolicy\").arg(\"Bypass\");")
    rust.append(f"  cmd.arg(script_path(\"{rel}\"));")
  elif stype in {"batch"}:
    rust.append("  let mut cmd = Command::new(\"cmd\");")
    rust.append("  cmd.arg(\"/C\");")
    rust.append(f"  cmd.arg(script_path(\"{rel}\"));")
  else:
    rust.append("  let mut cmd = Command::new(script_path(\"{rel}\"));")

  rust.append("  for a in args { cmd.arg(a); }")
  rust.append("  let out = cmd.output().map_err(|e| e.to_string())?;")
  rust.append("  if out.status.success() {")
  rust.append("    Ok(String::from_utf8_lossy(&out.stdout).to_string())")
  rust.append("  } else {")
  rust.append("    Err(String::from_utf8_lossy(&out.stderr).to_string())")
  rust.append("  }")
  rust.append("}")
  return "\n".join(rust)

def ts_binding_for(entry: Dict[str, Any]) -> str:
  name = entry["name"]
  func = name.replace(".", "_").replace("-", "_")
  return f"""
export async function runLegacy_{func}(args: string[]): Promise<string> {{
  return invoke<string>("run_legacy_{func}", {{ args }});
}}
""".strip()

def main() -> None:
  ap = argparse.ArgumentParser()
  ap.add_argument(
    "--report",
    default="tools/analysis/legacy_report.json",
    help="Path to analyzer JSON report",
  )
  ap.add_argument(
    "--out",
    default="tools/generated",
    help="Dir for generated outputs",
  )
  args = ap.parse_args()

  report = json.loads(Path(args.report).read_text(encoding="utf-8"))
  entries: List[Dict[str, Any]] = report["entries"]

  out_dir = Path(args.out)
  out_dir.mkdir(parents=True, exist_ok=True)

  rust_parts = [HEADER_RUST]
  ts_parts = [HEADER_TS]
  commands = []

  for e in entries:
    rust_parts.append(rust_cmd_for(e))
    ts_parts.append(ts_binding_for(e))
    commands.append(f"run_legacy_{e['name'].replace('.','_').replace('-','_')}")

  Path(out_dir / "legacy_wrappers.rs").write_text(
    "\n\n".join(rust_parts), encoding="utf-8"
  )
  Path(out_dir / "legacy_bindings.ts").write_text(
    "\n\n".join(ts_parts), encoding="utf-8"
  )

  # Print a helper snippet to register commands
  helper = "// Add to tauri::Builder invoke_handler:\n// ".join(
    [
      "tauri::generate_handler![\n  " + ",\n  ".join(commands) + "\n]"
    ]
  )
  Path(out_dir / "REGISTER_CMDS.txt").write_text(helper, encoding="utf-8")

  print(f"Generated: {out_dir/'legacy_wrappers.rs'}")
  print(f"Generated: {out_dir/'legacy_bindings.ts'}")
  print(f"See:       {out_dir/'REGISTER_CMDS.txt'}")

if __name__ == "__main__":
  main()